### ISSUE TITLE
I'm having a typerrore : abytes like object is required not str .

### ISSUE THREAD

**Issue by Mohammad-ezzidden** [alfanhui/mbtileToPng#1]

**Comment by philippe78** [comment]
Line 89. Change with   output_file.write(ablob.encode())

**Comment by FagundesCristianoF** [comment]
Change the  line 89 
`output_file.write(ablob) `

to 

`output_file.write(ablob.encode())`

**Comment by philippe78** [comment]
I don't think that it will solve the issue, I think that he is trying to use maps directly from openstreetmap,without processing as suggested on the documentation. 

Including these lines of code it will solve the exceptions, but the output are not png files.

**Comment by Swepilot** [comment]
I have the same problem as @Mohammad-ezzidden 

I'm using a .mbtiles file which is a custom extract from OpenMapTiles.com. Changing the code as suggested generated the files, but as @philippe78 said not valid .png files. 

Are the files from OpenMapTiles.com raster or vector files? I tried to (just in case) to convert from vector .mbtiles file to raster using this https://github.com/bjornreppen/rasterize-vector-tiles but then I got an error regarding a missing property in the source .mbtiles

**Comment by alfanhui** [comment]
I can't believe I missed these comments. My appologies for not seeing them to address them earlier.

@Swepilot 
OpenMapTiles.com states it offers both raster and vector files, but the downloads appear to only offer MBTiles (PBF). PBF is a vector format. This project will only work if the MBTiles are in raster format.

**Comment by alfanhui** [comment]
I've updated the readme to be clearer on rasterised .mbtiles usage only. Closing issue as I am certain this error is when using vectored based .mbtiles.
